### ISSUE TITLE
Persistency service: Implement "Project" interaction

### ISSUE THREAD

**Issue by ghost** [ProjectIndoor/projectindoorweb#18]
The persistency service will be implemented to connect the existing business functionality to a JPA-managed database and to enable REST interface functionality to work with "real" objects.

**Comment by VolkanKutlar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create persistency service](https://trello.com/c/kHKLsAaw/95-create-persistency-service)

**Comment by ghost** [comment]
Changed to name of the issue so it's more fine-grained concerning the entity classes. As a result, we can have a code commit for each of the entity classes and related JPA repository.
