### ISSUE TITLE
Extend getAllBuildings to also send image size and floors

### ISSUE THREAD

**Issue by Dobli** [ProjectIndoor/projectindoorweb#32]
Old response:

[

  {
    "buildingName": "string",
    "floorCount": 0,
    "id": 0
  }
]

New expected response:
`[
  {
    "buildingName": "string",
    "floorCount": 0,
    "id": 0
    "floors": [
                        {
                            floorNo: 0,
                            floorName: "UG1",
                            url: "/maps/hft_2_floor_0.png"
                        },
                        {
                            floorNo: 1,
                            floorName: "EG",
                            url: "/maps/hft_2_floor_1.png"
                        }
                    ],
                    "imagePixelWidth" = 3688,
                    "imagePixelHeight" = 2304
  }
]`

**Comment by Dobli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Import and use floors from backend](https://trello.com/c/cUHeRAGP/128-import-and-use-floors-from-backend)

**Comment by ghost** [comment]
Resolved by 080a0ca.
