### ISSUE TITLE
New REST Method: addFloorToBuilding

### ISSUE THREAD

**Issue by Dobli** [ProjectIndoor/projectindoorweb#34]
A method which allows to add a floor map and name to a building.
It should be using form-data as request type (see upload radiomap function)
Example:
[
  {
    "buildingIdentifier": 1,
    "floorIdentifier": 1,
    "floorName": "EG"
    "floorMap": FILE
  }
]

**Comment by Dobli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Import and use floors from backend](https://trello.com/c/cUHeRAGP/128-import-and-use-floors-from-backend)

**Comment by VolkanKutlar** [comment]
I added two new methods: addFloorToBuilding and deleteSelectedFloor. Needs connection to the backend @nicokrieg.
