### ISSUE TITLE
Modifie getAllAlgorithms method to also return algorithm parameters

### ISSUE THREAD

**Issue by VolkanKutlar** [ProjectIndoor/projectindoorweb#36]
Remove getAlgorithmParameterListForAlgorithmId method and return all parameters in getAllAlgorithms instead.

**Comment by VolkanKutlar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Change getAlgorithmParameterListForAlgorithmID to getAlgorithmParameterListForAlgorithm and implement it](https://trello.com/c/OeXmnjVm/131-change-getalgorithmparameterlistforalgorithmid-to-getalgorithmparameterlistforalgorithm-and-implement-it)

**Comment by ghost** [comment]
@VolkanKutlar Please review :)

**Comment by VolkanKutlar** [comment]
Smaller refactroign done, task can be closed.
