### ISSUE TITLE
Add delete methods for Projects, Buildings, Evaal files

### ISSUE THREAD

**Issue by VolkanKutlar** [ProjectIndoor/projectindoorweb#37]

**Comment by VolkanKutlar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add delete methods for Projects, Buildings, Evaal files](https://trello.com/c/O52VMbLN/132-add-delete-methods-for-projects-buildings-evaal-files)

**Comment by VolkanKutlar** [comment]
Rest interface is ready.

**Comment by ghost** [comment]
@VolkanKutlar @Dobli Guys, can I close this issue? It was resolved by one of the commits in the past week, but I forgot the reference the issue again. My bad.
