### ISSUE TITLE
Add REST endpoint to get all Evaal files

### ISSUE THREAD

**Issue by Dobli** [ProjectIndoor/projectindoorweb#38]
Another API enpoint is needed, it should provide a list of all evaal files (radiomap and evaluation).

**Expected endpoint**
```
/position/getAllEvaalEntries
```

**Expected parameters**
none

**Expected result**
An array containing evaal objects with: id, entryName, type (radiomap/evaluation), buildingName
```
[
  {
    "id": 1,
    "entryName": "radiomap.txt"
    "type": "radiomap"
    "buildingName": "HFT Building 2"
  },
  {
    "id": 2,
    "entryName": "evaluation.txt"
    "type": "evaluation"
    "buildingName": "HFT Building 2"
  }
]
```

**Comment by VolkanKutlar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add REST endpoint to get all Evaal files](https://trello.com/c/JK3Ct2u4/140-add-rest-endpoint-to-get-all-evaal-files)

**Comment by VolkanKutlar** [comment]
Rest endpoint now available. Returns an empty list at the moment though.
