### ISSUE TITLE
Implement mechanism to give back detailed warning and error information to frontend

### ISSUE THREAD

**Issue by VolkanKutlar** [ProjectIndoor/projectindoorweb#42]
Implement a functionality to check what the outcome of a current function call is, map it to an associated HTTP response and return that one with the correct function result object.

**Comment by VolkanKutlar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement mechanism to give back detailed warning and error information to frontend](https://trello.com/c/plwxXaID/138-implement-mechanism-to-give-back-detailed-warning-and-error-information-to-frontend)

**Comment by ghost** [comment]
fdc9587

**Comment by Dobli** [comment]
I've looked at the implementation for the messages. There is a little problem left. You send your messages directly in the body but do not define a content-type (e.g. text/plain). Now either spring uses a default one or firefox defaults to it, either way I get an application/json as content type. Now angular checks this and says the body is no json data and it is marked as erroneus even if it is a success message and the backend worked correctly.

There are two ways to solve this
1. The result is packed as JSON with a "message" key
2. Send the message using the response header

**Comment by VolkanKutlar** [comment]
Ok ill take a look at it tomorrow.
