### ISSUE TITLE
Use environment variables for temporary and peristent Files

### ISSUE THREAD

**Issue by Dobli** [ProjectIndoor/projectindoorweb#45]
**Current state**
Currently temporary files, which are created during processing of radiomap/evaluation files, are placed in the working directory (e.g. the project root folder during development).
Floor map uploads are persisted in `./src/main/resources/static/floor_maps`

**Problem**
Temporary files are not deleted and sum up, but are not needed anymore.
The location of persistent floor_maps depends on the working directory, so it may change between calls.

**Proposed Solution**
Use springs properties mechanism to get paths for the systems TEMP folders for temporary files and define an environment variable for the application.properties file which points to an floor_map directory (e.g. $HOME/.floor_map).
Default location of properties file: src/main/resources/application.properties

**Additional references**
Spring documentation: https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html

**Comment by ghost** [comment]
@Dobli @VolkanKutlar Please review :)

**Comment by VolkanKutlar** [comment]
From what I can see everything looks fine. No refactoring needed.

**Comment by ghost** [comment]
Alright, thanks. I suggest we wait for Alex' feedback and if he's happy as well, we'll close this issue.

**Comment by Dobli** [comment]
Would be nice to make it configurable using the application.properties file too (only for the floor map folder), but as it is now it is already better as I now have a folder I can point docker too, so yes you could close it :-).
