### ISSUE TITLE
Response of getAllProjects should contain buildingIds

### ISSUE THREAD

**Issue by schilli91** [ProjectIndoor/projectindoorweb#46]
The response of the said endpoint contains the building name but not the id, but I need to have the id in order to fetch the floors of this building. 

It would be great, if the response project model could be extended by the property `buildingId`.

![image](https://user-images.githubusercontent.com/28610231/34436523-dc8cf4a8-ec96-11e7-89a1-db7a9ede3be1.png)

**Comment by ghost** [comment]
@schilli91 Please review :)
