### ISSUE TITLE
Return error messages as json

### ISSUE THREAD

**Issue by Dobli** [ProjectIndoor/projectindoorweb#53]
Instead of returning plain text, provide the error messages as json responses.

**Example**

{
  "message": "Wrong file type for radiomap file"
}

**Comment by VolkanKutlar** [comment]
@Dobli bug fixed as requested. Please test.

**Comment by VolkanKutlar** [comment]
Ehhhhm @nicokrieg i think you committed into the wrong issue :D

**Comment by VolkanKutlar** [comment]
@Dobli if the bug is fixed you can close it. Error messages inside the wrapper are not part of this bug.

**Comment by Dobli** [comment]
Okay then I will close it for now :D
