### ISSUE TITLE
vendor file

### ISSUE THREAD

**Issue by Rajaune** [ProjectIndoor/projectindoorweb#54]
can not find the file 'vendor' to launch frotend

**Comment by Dobli** [comment]
The issue lacks proper information about the error, more details would be helpful.

But just in case I guessed right:
Have you executed all steps below "Installing" in the Getting Started section of the readme? Especially the following lines are needed to generate the vendor files:
```bash
# Preload client (JS) dependencies
./gradlew clientInstall
```

**Comment by Rajaune** [comment]
Thank u
